export   const POST_LIST_REQUEST = "POST_LIST_REQUEST"
export   const POST_LIST_SUCCESS = "POST_LIST_SUCCESS"
export   const POST_LIST_FAIL = "POST_LIST_FAIL"

export const POST_DETAIL_REQUEST = "POST_DETAIL_REQUEST"
export const POST_DETAIL_SUCCESS = "POST_DETAIL_SUCCESS"
export const POST_DETAIL_FAIL = "POST_DETAIL_FAIL"

